package tech.luigui.katas.puzzle_fighter;

import java.util.*;
import java.util.stream.*;


public class PuzzleFighterModelTest {

    private static final String[][][] FIXED_TESTS_MOVES = {
        {{"BR","LLL"},{"BY","LL"},{"BG","ALL"},{"BY","BRR"},{"RR","AR"},{"GY","A"},{"BB","AALLL"},{"GR","A"},{"RY","LL"},{"GG","L"},{"GY","BB"},{"bR","ALLL"},{"gy","AAL"}},
        {{"GR","ALLL"},{"GG","ALLL"},{"RG","AAL"},{"RB","BLL"},{"RG","ALL"},{"BB","RR"},{"BR","BB"},{"BR","ALLL"},{"YB","R"},{"BG","BBRR"},{"YR","AAR"},{"RR","L"},{"RR","ABLL"},{"GY","BRR"},{"BB","R"},{"gB","RR"},{"BR","ALL"},{"Gr","BB"},{"Rb","R"},{"GG","B"},{"bB","LL"}},
        {{"RR","LLL"},{"GG","LL"},{"RG","BBL"},{"GY","AR"},{"RR","BBLLL"},{"RB","AALL"},{"GR","B"},{"GB","AR"},{"RR",""},{"GG","R"},{"YR","BR"},{"RR","LLL"},{"BR","AALL"},{"Bg",""},{"RR","BBBBLLL"},{"GR","ALLL"},{"bR","L"},{"YG","BBBALL"},{"RR","L"},{"YB","AL"}},
        {{"YY","BALLL"},{"RR","AALL"},{"RG","BR"},{"YG","ALLR"},{"BG","BRR"},{"YR","BBLLLL"},{"GR","BL"},{"GG","ALB"},{"GY",""},{"yB","RR"},{"GG","R"},{"RB","LLLAAAB"},{"Ry","LL"},{"BG","BR"},{"RB","BBRRR"},{"Rg","R"},{"bR","L"},{"YR","BLLL"},{"RR","LLLLLLLL"},{"Yg","AALL"},{"Br","LLL"}},
        {{"BB","LLLL"},{"BB","LL"},{"BB","L"},{"BB","LLL"},{"BB","LL"},{"BG","L"},{"BB",""},{"BB","R"},{"RB","BBRRR"},{"RR","LLL"},{"RR","BALL"},{"RR",""},{"RR","R"},{"RR","L"},{"RR","B"},{"RR","LLL"},{"RR","LL"},{"RR","BLLL"},{"RR","B"},{"YR","ALL"},{"GR","AL"},{"Rb","RRRR"}},
        {{"RY","ALLL"},{"YY","L"},{"RG","BBR"},{"YR","BLL"},{"RR","ALLLL"},{"GY","B"},{"RR","RRRRRRR"},{"RY","ALLL"},{"BY","BBBBLL"},{"BY","L"},{"BG","BBBL"},{"BB","LLL"},{"BY","BBLL"},{"BR","AL"},{"RB","AR"},{"BB","RR"},{"GG","R"},{"YB","LLLRR"},{"GG",""},{"rb","RR"},{"bY","ABLL"},{"GY","L"},{"GR","BRR"},{"RR","LLL"},{"yy","LLLB"},{"RY","BB"}},
        {{"YR","LLL"},{"GY","LLLRL"},{"RY","BBLL"},{"RB","AAL"},{"GR","BR"},{"GG","A"},{"YY","LL"},{"GG","BLLL"},{"YY","ALLL"},{"BY","BL"},{"YB","ALLLR"},{"RY","LLLB"},{"GG","BBBBB"},{"GB","A"},{"GR","AA"},{"gB","AALAB"},{"YR","RRAAA"},{"BB",""},{"RG","AL"},{"GG","L"},{"RG","RRBL"},{"Gb","A"},{"rB","R"},{"GG","RR"},{"RB","AARR"},{"GG","BR"},{"bR","AARR"}},
        {{"BB","AALLL"},{"GR","RR"},{"RR","R"},{"RG","A"},{"YY","BBBL"},{"BG","RR"},{"BY",""},{"Rg","RR"},{"YB","A"},{"BY","RRAA"},{"BY","L"},{"yB","LLLBB"},{"YR","A"},{"Yy","BBB"},{"rY","BR"},{"Rb","BRR"},{"gR","ARR"},{"BB","B"},{"BG","B"},{"RG","BBLL"},{"YG","LLLA"},{"GG","L"},{"RY","BRR"},{"bB",""}},
        {{"GY","LL"},{"BG","R"},{"BB","BR"},{"GG","BR"},{"RG","AAL"},{"GB","BBRR"},{"YG","RR"},{"YG","BRR"},{"BG","LL"},{"GB",""},{"RR","R"},{"YR","AAAA"},{"RB","RRA"},{"YB","BB"},{"BY","LLLB"},{"bY","R"},{"GB","L"},{"RR","L"},{"0G","AARR"},{"RB","AAL"},{"GB","ALL"},{"yB","R"},{"Br","LLLA"},{"BY","L"},{"GR","ALL"},{"B0","L"},{"rY","ALL"},{"RB","ALLL"},{"BR","ALL"},{"RR","LLLLR"},{"GY","ALLL"},{"BB","LL"},{"0G","RRA"},{"yr","AALL"}},
        {{"RR","LLL"},{"RR","LLL"},{"GG","LLL"},{"RR","LLL"},{"YY","LL"},{"YY","LL"},{"BY","LL"},{"BG","L"},{"YY","L"},{"RR","LL"},{"BR","L"},{"Yb","AAL"},{"GG",""},{"BB","R"},{"GG","R"},{"GG",""},{"GB","BBRR"},{"BR",""},{"BY","RBR"},{"BB","RRRR"},{"BB","AARR"},{"yB","R"},{"Bg","A"},{"RR",""},{"Br",""}}
    };
    
    private static final String[] FIXED_TESTS_EXPECTEDS = {
        "      \n      \n      \n      \n      \n      \n      \n      \n      \n    R \n R  YR\nRR  RB",
        "      \n      \n      \n      \n      \n      \n      \n    R \n  GGY \n  GGYB\nGGGRYB\nGRRBBB",
        "      \n      \n      \nGG    \nRY    \nRRYB  \nRRRB  \nR RgY \nR RRG \nRRRRG \nRGGRGB\nRGRGGY",
        "      \n      \n      \n      \n      \n      \n      \n     B\n    RR\n  b gy\n  R BB\nBBYYRB",
        "      \n      \n      \n      \n YG   \nRRR   \nRRR   \nRRRR  \nRRRR  \nRRRR  \n   RRR\n  GRRR",
        "      \n      \n      \n      \n      \n      \nR  Y  \nR  RR \nR  GG \nR  GG \nR  G  \nRRGGGG",
        "      \n      \n      \n      \n      \n R    \n Y    \nYY    \nYY G  \n YGGG \nYYGGYG\nYY GBG",
        "      \n      \n      \n      \n      \n      \n      \n      \n  G   \n GG Y \n GG R \nYR RRR",
        "      \n Y    \n RR   \n RY   \n BB   \n BB   \n rY y \n GB BG\nGGBYYY\nRGGYGY\nBGGGGG\nYY GGG",
        "      \n      \n      \n      \nRR    \nRR    \nG Y   \nGYR   \nRYY   \nRYY   \nRY    \nRYBR G"
    };
    
    private static final String[][] FIXED_TESTS_STATES = {
       {
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nB     \nR     ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nBB    \nRY    ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n B    \nBB    \nRYG   ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n B    \nBB    \nRYG YB",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n B    \nBB  RR\nRYG YB",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n B  Y \nBB  RR\nRYGGYB",
           "      \n      \n      \n      \n      \n      \n      \n      \nB     \nBB  Y \nBB  RR\nRYGGYB",
           "      \n      \n      \n      \n      \n      \n      \n      \nB   R \nBB  Y \nBB GRR\nRYGGYB",
           "      \n      \n      \n      \n      \n      \n      \n R    \nBY  R \nBB  Y \nBB GRR\nRYGGYB",
           "      \n      \n      \n      \n      \n      \n      \n R    \nBY  R \nBBG Y \nBBGGRR\nRYGGYB",
           "      \n      \n      \n      \n      \n      \n      \n R    \nBY YR \nBBGGY \nBBGGRR\nRYGGYB",
           "      \n      \n      \n      \n      \n      \n      \n      \n R YR \n RGGY \n YGGRR\nRYGGYB",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n    R \n R  YR\nRR  RB"},
       {
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nGR    ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nGG    \nGR    ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nGGG   \nGRR   ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \nBR    \nGGG   \nGRR   ",
           "      \n      \n      \n      \n      \n      \n      \n      \n R    \nBRG   \nGGG   \nGRR   ",
           "      \n      \n      \n      \n      \n      \n      \n      \n R    \nBRG   \nGGG  B\nGRR  B",
           "      \n      \n      \n      \n      \n      \n      \n      \n R    \nBRG   \nGGGR B\nGRRB B",
           "      \n      \n      \n      \n      \n      \n      \n R    \nBR    \nBRG   \nGGGR B\nGRRB B",
           "      \n      \n      \n      \n      \n      \n      \n R    \nBR    \nBRG   \nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n      \n      \n      \n R    \nBR   G\nBRG  B\nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n      \n      \n      \n R    \nBR  RG\nBRG YB\nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n      \n      \n      \n RR   \nBRR RG\nBRG YB\nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n      \n R    \n R    \n RR   \nBRR RG\nBRG YB\nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n      \n R    \n R    \n RR YG\nBRR RG\nBRG YB\nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n      \n R  B \n R  B \n RR YG\nBRR RG\nBRG YB\nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n      \n R  Bg\n R  BB\n RR YG\nBRR RG\nBRG YB\nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n B    \n R  Bg\n RR BB\n RR YG\nBRR RG\nBRG YB\nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n      \n     g\n    BB\n    BG\nB   YG\nBBGGYB\nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n      \n      \n      \n    R \nB   Y \nBBGGYB\nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n      \n      \n      \n    R \nB GGY \nBBGGYB\nGGGRYB\nGRRBBB",
           "      \n      \n      \n      \n      \n      \n      \n    R \n  GGY \n  GGYB\nGGGRYB\nGRRBBB"},
       {
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nR     \nR     ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nRG    \nRG    ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nRGG   \nRGR   ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nRGG   \nRGR GY",
           "      \n      \n      \n      \n      \n      \n      \n      \nR     \nR     \nRGG   \nRGR GY",
           "      \n      \n      \n      \n      \n      \n      \n      \nRB    \nRR    \nRGG   \nRGR GY",
           "      \n      \n      \n      \n      \n      \n      \n      \nRB    \nRRR   \nRGG   \nRGRGGY",
           "      \n      \n      \n      \n      \n      \n      \n      \nRB    \nRRR   \nRGG GB\nRGRGGY",
           "      \n      \n      \n      \n      \n      \n      \n      \nRB    \nRRRR  \nRGGRGB\nRGRGGY",
           "      \n      \n      \n      \n      \n      \n      \n      \nRB  G \nRRRRG \nRGGRGB\nRGRGGY",
           "      \n      \n      \n      \n      \n      \n      \n    Y \nRB RG \nRRRRG \nRGGRGB\nRGRGGY",
           "      \n      \n      \n      \n      \n      \nR     \nR   Y \nRB RG \nRRRRG \nRGGRGB\nRGRGGY",
           "      \n      \n      \n      \n      \n      \nRR    \nRB  Y \nRB RG \nRRRRG \nRGGRGB\nRGRGGY",
           "      \n      \n      \n      \n      \n      \nRR B  \nRB gY \nRB RG \nRRRRG \nRGGRGB\nRGRGGY",
           "      \n      \n      \n      \nR     \nR     \nRR B  \nRB gY \nRB RG \nRRRRG \nRGGRGB\nRGRGGY",
           "      \n      \n      \nG     \nR     \nRR    \nRR B  \nRB gY \nRB RG \nRRRRG \nRGGRGB\nRGRGGY",
           "      \n      \n      \nG     \nR     \nRR    \nRR B  \nR  gY \nR RRG \nRRRRG \nRGGRGB\nRGRGGY",
           "      \n      \n      \nGG    \nRY    \nRR    \nRR B  \nR  gY \nR RRG \nRRRRG \nRGGRGB\nRGRGGY",
           "      \n      \n      \nGG    \nRY    \nRR    \nRRRB  \nR RgY \nR RRG \nRRRRG \nRGGRGB\nRGRGGY",
           "      \n      \n      \nGG    \nRY    \nRRYB  \nRRRB  \nR RgY \nR RRG \nRRRRG \nRGGRGB\nRGRGGY"},
       {
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nY     \nY     ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nYR    \nYR    ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nYR    \nYR GR ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nYR G  \nYRYGR ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nYR GG \nYRYGRB",
           "      \n      \n      \n      \n      \n      \n      \n      \nR     \nY     \nYR GG \nYRYGRB",
           "      \n      \n      \n      \n      \n      \n      \n      \nR     \nYR    \nYRGGG \nYRYGRB",
           "      \n      \n      \n      \n      \n      \n      \n      \nR G   \nYRG   \nYRGGG \nYRYGRB",
           "      \n      \n      \n      \n      \n      \n      \n      \nR GG  \nYRGY  \nYRGGG \nYRYGRB",
           "      \n      \n      \n      \n      \n      \n      \n      \nR GG  \nYRGY y\nYRGGGB\nYRYGRB",
           "      \n      \n      \n      \n      \n      \n      \n      \nR GGG \nYRGYGy\nYRGGGB\nYRYGRB",
           "      \n      \n      \n      \n      \n      \n      \n B    \nRRGGG \nYRGYGy\nYRGGGB\nYRYGRB",
           "      \n      \n      \n      \n      \n R    \n y    \n B    \nRRGGG \nYRGYGy\nYRGGGB\nYRYGRB",
           "      \n      \n      \n      \n      \n R    \n y    \n B GB \nRRGGG \nYRGYGy\nYRGGGB\nYRYGRB",
           "      \n      \n      \n      \n      \n R    \n y    \n B GBB\nRRGGGR\nYRGYGy\nYRGGGB\nYRYGRB",
           "      \n      \n      \n      \n      \n R  R \n y  g \n B GBB\nRRGGGR\nYRGYGy\nYRGGGB\nYRYGRB",
           "      \n      \n      \n      \n      \n R  R \n yb g \n BRGBB\nRRGGGR\nYRGYGy\nYRGGGB\nYRYGRB",
           "      \n      \n      \n      \n Y    \n R  R \n yb g \nRBRGBB\nRRGGGR\nYRGYGy\nYRGGGB\nYRYGRB",
           "      \n      \n      \n      \n Y    \nRR  R \nRyb g \nRBRGBB\nRRGGGR\nYRGYGy\nYRGGGB\nYRYGRB",
           "      \n      \n g    \n Y    \n Y    \nRR  R \nRyb g \nRBRGBB\nRRGGGR\nYRGYGy\nYRGGGB\nYRYGRB",
           "      \n      \n      \n      \n      \n      \n      \n     B\n    RR\n  b gy\n  R BB\nBBYYRB"},
       {
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nB     \nB     ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nBB    \nBB    ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nBBB   \nBBB   ",
           "      \n      \n      \n      \n      \n      \n      \n      \nB     \nB     \nBBB   \nBBB   ",
           "      \n      \n      \n      \n      \n      \n      \n      \nBB    \nBB    \nBBB   \nBBB   ",
           "      \n      \n      \n      \n      \n      \n      \n      \nBBB   \nBBG   \nBBB   \nBBB   ",
           "      \n      \n      \n      \n      \n      \n      \n      \nBBB   \nBBG   \nBBBB  \nBBBB  ",
           "      \n      \n      \n      \n      \n      \n      \n      \nBBB   \nBBG   \nBBBBB \nBBBBB ",
           "      \n      \n      \n      \n      \n      \n      \n      \nBBB   \nBBG   \nBBBBBB\nBBBBBR",
           "      \n      \n      \n      \n      \n      \nR     \nR     \nBBB   \nBBG   \nBBBBBB\nBBBBBR",
           "      \n      \n      \n      \n      \n      \nRR    \nRR    \nBBB   \nBBG   \nBBBBBB\nBBBBBR",
           "      \n      \n      \n      \n      \n      \nRR    \nRR    \nBBBR  \nBBGR  \nBBBBBB\nBBBBBR",
           "      \n      \n      \n      \n      \n      \nRR    \nRR    \nBBBRR \nBBGRR \nBBBBBB\nBBBBBR",
           "      \n      \n      \n      \n      \n      \nRRR   \nRRR   \nBBBRR \nBBGRR \nBBBBBB\nBBBBBR",
           "      \n      \n      \n      \n      \n  R   \nRRR   \nRRRR  \nBBBRR \nBBGRR \nBBBBBB\nBBBBBR",
           "      \n      \n      \n      \nR     \nR R   \nRRR   \nRRRR  \nBBBRR \nBBGRR \nBBBBBB\nBBBBBR",
           "      \n      \n      \n      \nRR    \nRRR   \nRRR   \nRRRR  \nBBBRR \nBBGRR \nBBBBBB\nBBBBBR",
           "      \n      \n      \nRR    \nRR    \nRRR   \nRRR   \nRRRR  \nBBBRR \nBBGRR \nBBBBBB\nBBBBBR",
           "      \n      \n      \nRR    \nRRR   \nRRR   \nRRRR  \nRRRR  \nBBBRR \nBBGRR \nBBBBBB\nBBBBBR",
           "      \n      \n Y    \nRRR   \nRRR   \nRRR   \nRRRR  \nRRRR  \nBBBRR \nBBGRR \nBBBBBB\nBBBBBR",
           "      \n      \n YG   \nRRR   \nRRR   \nRRRR  \nRRRR  \nRRRR  \nBBBRR \nBBGRR \nBBBBBB\nBBBBBR",
           "      \n      \n      \n      \n YG   \nRRR   \nRRR   \nRRRR  \nRRRR  \nRRRR  \n   RRR\n  GRRR"},
       {
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nRY    ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \n  Y   \nRYY   ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \n  Y G \nRYY R ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nRYY G \nRYY R ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \nRR    \nRYY G \nRYY R ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \nRRY   \nRYY G \nRYYGR ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \nRRY   \nRYY GR\nRYYGRR",
           "      \n      \n      \n      \n      \n      \n      \n      \nRY    \nRRY   \nRYY GR\nRYYGRR",
           "      \n      \n      \n      \n      \n      \n B    \n Y    \nRY    \nRRY   \nRYY GR\nRYYGRR",
           "      \n      \n      \n      \n      \n      \n B    \n YB   \nRYY   \nRRY   \nRYY GR\nRYYGRR",
           "      \n      \n      \n      \n      \n      \n BB   \n YB   \nRYY   \nRRY   \nRYYGGR\nRYYGRR",
           "      \n      \n      \n      \n      \n      \nBBB   \nBYB   \nRYY   \nRRY   \nRYYGGR\nRYYGRR",
           "      \n      \n      \n      \n Y    \n B    \nBBB   \nBYB   \nRYY   \nRRY   \nRYYGGR\nRYYGRR",
           "      \n      \n      \n      \n Y    \n BB   \nBBB   \nBYB   \nRYY   \nRRYR  \nRYYGGR\nRYYGRR",
           "      \n      \n      \n      \n Y    \n BB   \nBBB   \nBYB   \nRYY   \nRRYRRB\nRYYGGR\nRYYGRR",
           "      \n      \n      \n      \n Y    \n BB   \nBBB   \nBYB  B\nRYY  B\nRRYRRB\nRYYGGR\nRYYGRR",
           "      \n      \n      \n      \n Y    \n BB   \nBBB   \nBYB GB\nRYY GB\nRRYRRB\nRYYGGR\nRYYGRR",
           "      \n      \n      \n  Y   \n YB   \n BB   \nBBB   \nBYB GB\nRYY GB\nRRYRRB\nRYYGGR\nRYYGRR",
           "      \n      \n      \n  Y   \n YB   \n BB   \nBBB   \nBYBGGB\nRYYGGB\nRRYRRB\nRYYGGR\nRYYGRR",
           "      \n      \n      \n  Y   \n YB   \n BB   \nBBB   \nBYB   \nRYYGG \nRRYGG \nRYYG  \nRYYGG ",
           "      \n      \n b    \n YY   \n YB   \n BB   \nBBB   \nBYB   \nRYYGG \nRRYGG \nRYYG  \nRYYGG ",
           "      \n  G   \n bY   \n YY   \n YB   \n BB   \nBBB   \nBYB   \nRYYGG \nRRYGG \nRYYG  \nRYYGG ",
           "      \n  G   \n bY   \n YY   \n YB   \n BB   \nBBB   \nBYB R \nRYYGG \nRRYGG \nRYYG  \nRYYGGG",
           "      \n  G   \n bY   \n YY   \nRYB   \nRBB   \nBBB   \nBYB R \nRYYGG \nRRYGG \nRYYG  \nRYYGGG",
           "      \n      \n      \n      \n      \n      \nR     \nR   R \nR  GG \nR  GG \nR  G  \nRRGGGG",
           "      \n      \n      \n      \n      \n      \nR  Y  \nR  RR \nR  GG \nR  GG \nR  G  \nRRGGGG"},
       {
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nY     \nR     ",
           "      \n      \n      \n      \n      \n      \n      \n      \nG     \nY     \nY     \nR     ",
           "      \n      \n      \n      \n      \n      \n      \n      \nG     \nY     \nYY    \nRR    ",
           "      \n      \n      \n      \n      \n      \n      \n      \nG     \nY     \nYYB   \nRRR   ",
           "      \n      \n      \n      \n      \n      \n      \n      \nG     \nY     \nYYB   \nRRRRG ",
           "      \n      \n      \n      \n      \n      \n      \n      \nG     \nY     \nYYBGG \nRRRRG ",
           "      \n      \n      \n      \n      \n      \n      \n      \nGY    \nYY    \nYYBGG \nRRRRG ",
           "      \n      \n      \n      \n      \n      \n      \nGG    \nGY    \nYY    \nYYBGG \nRRRRG ",
           "      \n      \n      \n      \n      \n      \nYY    \nGG    \nGY    \nYY    \nYYBGG \nRRRRG ",
           "      \n      \n      \n      \n      \n Y    \nYY    \nGG    \nGY    \nYYB   \nYYBGG \nRRRRG ",
           "      \n      \n      \n      \n Y    \n Y    \nYY    \nGG    \nGYB   \nYYB   \nYYBGG \nRRRRG ",
           "      \n      \n      \n R    \n Y    \nYY    \nYY    \nGG    \nGYB   \nYYB   \nYYBGG \nRRRRG ",
           "      \n      \n      \n R    \n Y    \nYY    \nYY    \nGGG   \nGYB   \nYYBG  \nYYBGG \nRRRRG ",
           "      \n      \n      \n R    \n Y    \nYY    \nYY    \nGGG   \nGYBG  \nYYBGB \nYYBGG \nRRRRG ",
           "      \n      \n      \n R    \n Y    \nYY    \nYY R  \nGGGG  \nGYBG  \nYYBGB \nYYBGG \nRRRRG ",
           "      \n      \n      \n      \n R    \n Y    \nYY    \nYYB   \n YB   \nYYB   \nYYBR  \nRRRRB ",
           "      \n      \n      \n      \n R    \n Y    \nYY    \nYYB   \n YB   \nYYBR  \nYYBRY \nRRRRB ",
           "      \n      \n      \n      \n R    \n Y    \nYY    \nYYBB  \n YBB  \nYYBR  \nYYBRY \nRRRRB ",
           "      \n      \n      \n      \n R    \n Y    \nYYRG  \nYYBB  \n YBB  \nYYBR  \nYYBRY \nRRRRB ",
           "      \n      \n      \n      \n RG   \n YG   \nYYRG  \nYYBB  \n YBB  \nYYBR  \nYYBRY \nRRRRB ",
           "      \n      \n      \n      \n RG   \n YGG  \nYYRG  \nYYBB  \n YBB  \nYYBRR \nYYBRY \nRRRRB ",
           "      \n      \n      \n      \n R    \n Y    \nYYGG  \nYYGG  \n Y G  \nYY RR \nYYRRY \nRRRRB ",
           "      \n      \n      \n      \n R    \n Y    \nYYGG  \nYYGGr \n Y GB \nYY RR \nYYRRY \nRRRRB ",
           "      \n      \n      \n      \n R    \n Y    \nYYGG  \nYYGGr \n Y GB \nYY RR \nYYRRYG\nRRRRBG",
           "      \n      \n      \n      \n R    \n Y    \nYYGG  \nYYGGr \n Y GBB\nYY RRR\nYYRRYG\nRRRRBG",
           "      \n      \n      \n      \n R    \n Y G  \nYYGGG \nYYGGr \n Y GBB\nYY RRR\nYYRRYG\nRRRRBG",
           "      \n      \n      \n      \n      \n R    \n Y    \nYY    \nYY G  \n YGGG \nYYGGYG\nYY GBG"},
       {
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nB     \nB     ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nB    G\nB    R",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nB   RG\nB   RR",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n    G \nB   RG\nB  RRR",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n    G \nB  YRG\nB YRRR",
           "      \n      \n      \n      \n      \n      \n      \n      \n     B\n    GG\nB  YRG\nB YRRR",
           "      \n      \n      \n      \n      \n      \n      \n      \n   B B\n   YGG\nB  YRG\nB YRRR",
           "      \n      \n      \n      \n      \n      \n     R\n     g\n   B B\n   YGG\nB  YRG\nB YRRR",
           "      \n      \n      \n      \n      \n      \n     R\n   Y g\n   BBB\n   YGG\nB  YRG\nB YRRR",
           "      \n      \n      \n      \n      \n      \n    YR\n   YBg\n   BBB\n   YGG\nB  YRG\nB YRRR",
           "      \n      \n      \n      \n      \n      \n    YR\n   YBg\n   BBB\n  BYGG\nB YYRG\nB YRRR",
           "      \n      \n      \n      \n      \n      \n    YR\n    Bg\n    BB\n   YGG\nB  BRG\nBBBRRR",
           "      \n      \n      \n      \n      \n    R \n    YR\n    Bg\n   YBB\n   YGG\nB  BRG\nBBBRRR",
           "      \n      \n      \n      \n    y \n    R \n    YR\n   YBg\n   YBB\n   YGG\nB  BRG\nBBBRRR",
           "      \n      \n      \n    r \n    y \n    R \n   YYR\n   YBg\n   YBB\n   YGG\nB  BRG\nBBBRRR",
           "      \n      \n    b \n    r \n    y \n    RR\n   YYR\n   YBg\n   YBB\n   YGG\nB  BRG\nBBBRRR",
           "      \n    g \n    b \n    r \n    yR\n    RR\n   YYR\n   YBg\n   YBB\n   YGG\nB  BRG\nBBBRRR",
           "      \n    g \n    b \n    r \n    yR\n   BRR\n   YYR\n   YBg\n   YBB\n   YGG\nB BBRG\nBBBRRR",
           "      \n    g \n    b \n    r \n   ByR\n   BRR\n   YYR\n   YBg\n   YBB\n  GYGG\nB BBRG\nBBBRRR",
           "      \n    g \n    b \n    r \n   ByR\n   BRR\n   YYR\n   YBg\n   YBB\n GGYGG\nBRBBRG\nBBBRRR",
           "      \n    g \n    b \n    r \n   ByR\n   BRR\n   YYR\n   YBg\n G YBB\nYGGYGG\nBRBBRG\nBBBRRR",
           "      \n    g \n    b \n    r \n   ByR\n   BRR\n   YYR\n  GYBg\n GGYBB\nYGGYGG\nBRBBRG\nBBBRRR",
           "      \n      \n      \n      \n      \n    Y \n    g \n  G Bg\n GG BB\nYGG GG\nBRBBRG\nBBBRRR",
           "      \n      \n      \n      \n      \n      \n      \n      \n  G   \n GG Y \n GG R \nYR RRR"},
       {
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \n G    \n Y    ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \n G  B \n Y  G ",
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n    B \n G  B \n Y BG ",
           "      \n      \n      \n      \n      \n      \n      \n      \n    G \n    B \n G GB \n Y BG ",
           "      \n      \n      \n      \n      \n      \n      \n      \n    G \n    B \n GGGB \n YRBG ",
           "      \n      \n      \n      \n      \n      \n      \n      \n    G \n    B \n GGGBB\n YRBGG",
           "      \n      \n      \n      \n      \n      \n      \n      \n    GY\n    BG\n GGGBB\n YRBGG",
           "      \n      \n      \n      \n      \n      \n      \n    GY\n    GY\n    BG\n GGGBB\n YRBGG",
           "      \n      \n      \n      \n      \n      \n      \n    GY\n B  GY\n G  BG\n GGGBB\n YRBGG",
           "      \n      \n      \n      \n      \n      \n      \n    GY\n B GGY\n G BBG\n GGGBB\n YRBGG",
           "      \n      \n      \n      \n      \n    R \n    R \n    GY\n B GGY\n G BBG\n GGGBB\n YRBGG",
           "      \n      \n      \n      \n      \n    R \n   YR \n   RGY\n B GGY\n G BBG\n GGGBB\n YRBGG",
           "      \n      \n      \n      \n    R \n    R \n   YRB\n   RGY\n B GGY\n G BBG\n GGGBB\n YRBGG",
           "      \n      \n      \n      \n   BR \n   YR \n   YRB\n   RGY\n B GGY\n G BBG\n GGGBB\n YRBGG",
           "      \n      \n      \n      \n   BR \n   YR \n   YRB\n B RGY\n B GGY\n G BBG\n GGGBB\nYYRBGG",
           "      \n      \n    b \n    Y \n   BR \n   YR \n   YRB\n B RGY\n B GGY\n G BBG\n GGGBB\nYYRBGG",
           "      \n      \n    b \n    Y \n   BR \n   YR \n   YRB\n B RGY\n BGGGY\n GBBBG\n GGGBB\nYYRBGG",
           "      \n      \n    b \n    Y \n   BR \n   YR \n  RYRB\n BRRGY\n BGGGY\n GBBBG\n GGGBB\nYYRBGG",
           "      \n      \n      \n      \n      \n    Y \n    R \n  RYRG\n  RYRY\n GGRGY\n GGGGG\nYYRGGG",
           "      \n      \n      \n      \n      \n  B Y \n  R R \n  RYRG\n  RYRY\n GGRGY\n GGGGG\nYYRGGG",
           "      \n      \n      \n      \n  B   \n  B Y \n  R R \n  RYRG\n GRYRY\n GGRGY\n GGGGG\nYYRGGG",
           "      \n      \n      \n    y \n  B B \n  B Y \n  R R \n  RYRG\n GRYRY\n GGRGY\n GGGGG\nYYRGGG",
           "      \n      \n      \n    y \n    B \n    Y \n    R \n  BYRG\n GBYRY\n GGRGY\nBGGGGG\nYYRGGG",
           "      \n      \n      \n    y \n    B \n  B Y \n  Y R \n  BYRG\n GBYRY\n GGRGY\nBGGGGG\nYYRGGG",
           "      \n      \n      \n    y \n  R B \n  B Y \n  Y R \n GBYRG\n GBYRY\n GGRGY\nBGGGGG\nYYRGGG",
           "      \n      \n      \n      \n  B   \n  B   \n  Y y \n GB BG\n GBYYY\n GGYGY\nBGGGGG\nYY GGG",
           "      \n      \n      \n  Y   \n  B   \n  B   \n rY y \n GB BG\n GBYYY\n GGYGY\nBGGGGG\nYY GGG",
           "      \n      \n      \n  Y   \n  B   \n BB   \n rY y \n GB BG\n GBYYY\nRGGYGY\nBGGGGG\nYY GGG",
           "      \n      \n  R   \n  Y   \n BB   \n BB   \n rY y \n GB BG\n GBYYY\nRGGYGY\nBGGGGG\nYY GGG",
           "      \n      \n RR   \n RY   \n BB   \n BB   \n rY y \n GB BG\n GBYYY\nRGGYGY\nBGGGGG\nYY GGG",
           "      \n Y    \n RR   \n RY   \n BB   \n BB   \n rY y \n GB BG\nGGBYYY\nRGGYGY\nBGGGGG\nYY GGG"},
       {
           "      \n      \n      \n      \n      \n      \n      \n      \n      \n      \nR     \nR     ",
           "      \n      \n      \n      \n      \n      \n      \n      \nR     \nR     \nR     \nR     ",
           "      \n      \n      \n      \n      \n      \nG     \nG     \nR     \nR     \nR     \nR     ",
           "      \n      \n      \n      \nR     \nR     \nG     \nG     \nR     \nR     \nR     \nR     ",
           "      \n      \n      \n      \nR     \nR     \nG     \nG     \nR     \nR     \nRY    \nRY    ",
           "      \n      \n      \n      \nR     \nR     \nG     \nG     \nRY    \nRY    \nRY    \nRY    ",
           "      \n      \n      \n      \nR     \nR     \nGB    \nGY    \nRY    \nRY    \nRY    \nRY    ",
           "      \n      \n      \n      \nR     \nR     \nGB    \nGY    \nRY    \nRY    \nRYB   \nRYG   ",
           "      \n      \n      \n      \nR     \nR     \nGB    \nGY    \nRYY   \nRYY   \nRYB   \nRYG   ",
           "      \n      \n      \n      \nRR    \nRR    \nGB    \nGY    \nRYY   \nRYY   \nRYB   \nRYG   ",
           "      \n      \n      \n      \nRR    \nRR    \nGBB   \nGYR   \nRYY   \nRYY   \nRYB   \nRYG   ",
           "      \n      \n      \n      \nRRb   \nRRY   \nGBB   \nGYR   \nRYY   \nRYY   \nRYB   \nRYG   ",
           "      \n      \n      \n      \nRRb   \nRRY   \nGBB   \nGYR   \nRYY   \nRYY   \nRYBG  \nRYGG  ",
           "      \n      \n      \n      \nRRb   \nRRY   \nGBB   \nGYR   \nRYY   \nRYY   \nRYBGB \nRYGGB ",
           "      \n      \n      \n      \nRRb   \nRRY   \nGBB   \nGYR   \nRYY G \nRYY G \nRYBGB \nRYGGB ",
           "      \n      \n      \n      \nRRb   \nRRY   \nGBB   \nGYR   \nRYYGG \nRYYGG \nRYBGB \nRYGGB ",
           "      \n      \n      \n      \nRRb   \nRRY   \nGBB   \nGYR   \nRYYGG \nRYYGG \nRYBGBB\nRYGGBG",
           "      \n      \n      \n      \nRRb   \nRRY   \nGBBB  \nGYRR  \nRYYGG \nRYYGG \nRYBGBB\nRYGGBG",
           "      \n      \n      \n      \nRRb   \nRRY   \nGBBB  \nGYRRY \nRYYGG \nRYYGGB\nRYBGBB\nRYGGBG",
           "      \n      \n      \n      \nRRb   \nRRY   \nGBBB  \nGYRRYB\nRYYGGB\nRYYGGB\nRYBGBB\nRYGGBG",
           "      \n      \n      \n      \nRRb   \nRRY  B\nGBBB B\nGYRRYB\nRYYGGB\nRYYGGB\nRYBGBB\nRYGGBG",
           "      \n      \n      \n      \nRRb   \nRRY yB\nGBBBBB\nGYRRYB\nRYYGGB\nRYYGGB\nRYBGBB\nRYGGBG",
           "      \n      \n      \n      \nRRb g \nRRYByB\nGBBBBB\nGYRRYB\nRYYGGB\nRYYGGB\nRYBGBB\nRYGGBG",
           "      \n      \n      \n   R  \nRRbRg \nRRYByB\nGBBBBB\nGYRRYB\nRYYGGB\nRYYGGB\nRYBGBB\nRYGGBG",
           "      \n      \n      \n      \nRR    \nRR    \nG Y   \nGYR   \nRYY   \nRYY   \nRY    \nRYBR G"}
   };

	public static String[][][] getFixedTestsMoves() {
		return FIXED_TESTS_MOVES;
	}

	public static String[] getFixedTestsExpecteds() {
		return FIXED_TESTS_EXPECTEDS;
	}

	public static String[][] getFixedTestsStates() {
		return FIXED_TESTS_STATES;
	}
}
